export enum VehicleCategory {
  MICRO_URBAN = 'MICRO_URBAN',
  MINI_CITY = 'MINI_CITY',
  VERSATILE_CITY = 'VERSATILE_CITY',
  COMPACT = 'COMPACT',
  SMALL_SEDAN = 'SMALL_SEDAN',
  MEDIUM_SEDAN = 'MEDIUM_SEDAN',
  LARGE_SEDAN = 'LARGE_SEDAN',
  SUV = 'SUV',
}
