name: Deploy Anngular app to Github Project

on:
  push:
    branches:
      - master
jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: All things angular
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v.1.4.0
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }} 
        build_configuration: production
        base_href: /app-covoiturage-front/  
        deploy_branch: gh-pages
        angular_dist_build_folder: dist/app-covoiturage-front/browser

permissions:
  contents: write
